### ISSUE TITLE
Failed ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by Henry1970** [serpentacademy/Send-Sol-with-JS-and-HTML#1]
Hi, conect perfect but i get this error in Chrome when i use send button.

test.html:70 Failed ReferenceError: Buffer is not defined
    at toBufferLE (browser.js:48:24)
    at Blob$1.bigIntLayout.encode (bigint.mjs:13:21)
    at Structure.encode (Layout.js:1092:36)
    at encodeData (instruction.ts:32:15)
    at Function.transfer (system-program.ts:788:14)
    at test.html:59:50

Somebody can help me? 
Thanks ¡¡¡¡¡

**Comment by serpentacademy** [comment]
Hi you can use a previous version of web3.js this CDN is working <script src="https://unpkg.com/@solana/web3.js@v1.33.0/lib/index.iife.js"></script>
But it would be better to use React + Wallet Adapter -> https://github.com/serpentacademy/Send-Sol-with-Wallet-Adapter-to-ANY-Wallet-React
Hope this helps!

**Comment by Henry1970** [comment]
Works ¡
Thank you very much ¡
You're the best.
I will keep you in mind in the future.
Cheers ¡
Henry
